#!/bin/bash

echo "Pre-push hook started..."

FILE="version"

if [ ! -f "$FILE" ]; then
    echo "Version file not found!"
    exit 1
fi

CURRENT_VERSION=$(cat $FILE)

git push origin "v$CURRENT_VERSION"