#!/bin/bash

echo "Pre-commit hook started..."

CONFIG="version"
SPEC_LOCAL="spec/local-api.yml"

if [ ! -f "$CONFIG" ]; then
    echo "config file not found!"
    exit 1
fi

CURRENT_VERSION=$(grep -m 1 '^version:' "$CONFIG" | awk '{print $2}')
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
PATCH=$((PATCH + 1))
NEW_VERSION="$MAJOR.$MINOR.$PATCH"
sed -i "s/^version: .*/version: $NEW_VERSION/" "$CONFIG"
sed -i "s/\(version:\) [0-9]\+\.[0-9]\+\.[0-9]\+/\1 $NEW_VERSION/" "$SPEC_LOCAL"
git add "$CONFIG"
git add "$SPEC_LOCAL"
git tag -a "v$NEW_VERSION" -m "Release version $NEW_VERSION"
echo "Version updated to $NEW_VERSION and tag created."