version: 0.2.44
node:
  bootstrap:
    - "/ip4/207.154.221.44/tcp/4001/p2p/12D3KooWJAqBh1FFmFAo6wxSYKYYPuSAzEaoorPx2oiwyuAQxtZu"
    - "/ip4/152.42.225.242/tcp/4001/p2p/12D3KooWJAYu4meUU7v5usd7P4b5LAJjBH6svwmGZqoVe24rLEQo"
    - "/ip4/152.42.230.9/tcp/4001/p2p/12D3KooWLJFqhpSJeMATLuHyHBo6qgAusACGhZLybtwVz3jGGfXy"
  port: 4001
  network_prefix: testnet
database:
  dirName: storage
server:
  host: localhost
  port: 4002
logging:
  level: info

