version: 0.2.30
node:
  bootstrap:
    - "/ip4/67.207.72.168/tcp/4001/p2p/12D3KooWFUASCJ2cnXUF4oJ1WivPFgpSDUkJ9pPMVnxZehK67n6c"
    - "/ip4/167.99.29.177/tcp/4001/p2p/12D3KooWHMbdTtoBU1k9cN6jdxqNwXaVub8XoYNKjYqb96egzXKc"
    - "/ip4/188.166.204.43/tcp/4001/p2p/12D3KooWBjmsi5CnpW7P98yykZSLZSCYAcUPxPww87KpsUWi9CVm"
  port: 4001
  network_prefix: testnet
database:
  dirName: storage
server:
  host: localhost
  port: 4002
logging:
  level: info

