version: 0.1.115
node:
  bootstrap:
    - "/ip4/67.207.72.168/tcp/4001/p2p/12D3KooWNoJgU3hkxQRdFCWwTYLAj7MmaZ1fnyBvHWhdbTyney6W"
  port: 4001
  network_prefix: 'warpnet'
database:
  dirName: "storage"
server:
  host: localhost
  port: 4002
logging:
  level: debug

