version: 0.2.29
node:
  bootstrap:
    - "/ip4/67.207.72.168/tcp/4001/p2p/12D3KooWAhKDDne1FzUwv6YPSh9puiXYXDF8TShuqEEEEBcphy1j"
    - "/ip4/167.99.29.177/tcp/4001/p2p/12D3KooWJrsV1rBUAWfDKQHha33a9anJirBGWJQirFUNpr4kTcP7"
    - "/ip4/188.166.204.43/tcp/4001/p2p/12D3KooWSDabe8gkFANTuVoYswYKkimAhA7JUG8vUiM4pJTd6aux"
  port: 4001
  network_prefix: testnet
database:
  dirName: storage
server:
  host: localhost
  port: 4002
logging:
  level: info

