bootstrap:
  id: 1
  enabled: false
  hosts:
    - "/ip4/188.166.192.56/tcp/4001/p2p/12D3KooWJAqBh1FFmFAo6wxSYKYYPuSAzEaoorPx2oiwyuAQxtZu"
    - "/ip4/188.166.192.56/tcp/4002/p2p/12D3KooWJAqBh1FFmFAo6wxSYKYYPuSAzEaoorPx2oiwyuAQxtZu"
server:
  port: 6969
database:
  path: ""