services:
  warpnet1:
    container_name: warpnet1
    image: ghcr.io/filinvadim/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4001
      - NODE_HOST=${NODE_HOST}
      - LOGGING_LEVEL=DEBUG
    volumes:
    - snapshot1:/tmp/snapshot:rw

  warpnet2:
    container_name: warpnet2
    image: ghcr.io/filinvadim/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4002
      - NODE_HOST=${NODE_HOST}
      - LOGGING_LEVEL=DEBUG
    volumes:
    - snapshot2:/tmp/snapshot:rw

  warpnet3:
    container_name: warpnet3
    image: ghcr.io/filinvadim/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4003
      - NODE_HOST=${NODE_HOST}
      - LOGGING_LEVEL=DEBUG

    volumes:
    - snapshot3:/tmp/snapshot:rw

volumes:
  snapshot1:
  snapshot2:
  snapshot3: