services:
  warpnet1:
    image: ghcr.io/filinvadim/warpnet:latest
    hostname: warpnet1
    ports:
      - "67.207.72.168:4001:4001"
    networks:
      - warpnet
    restart: always

  warpnet2:
    image: ghcr.io/filinvadim/warpnet:latest
    hostname: warpnet2
    ports:
      - "67.207.72.168:4002:4002"
    networks:
      - warpnet
    restart: always
    environment:
      - NODE_PORT=4002

  warpnet3:
    image: ghcr.io/filinvadim/warpnet:latest
    hostname: warpnet3
    ports:
      - "67.207.72.168:4003:4003"
    networks:
      - warpnet
    restart: always
    environment:
      - NODE_PORT=4003


networks:
  warpnet:
    driver: bridge
