services:
  bootstrap-node-vadim: # change host name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4011:4001"
      - "4012:4002"
    networks:
      - warpnet-network

networks:
  warpnet-network:
    driver: bridge
