services:
  warpnet1:
    container_name: warpnet1
    image: ghcr.io/filinvadim/warpnet:latest
    hostname: warpnet1
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4001
      - NODE_HOST=207.154.221.44
    volumes:
      - $HOME/storage

  warpnet2:
    container_name: warpnet2
    image: ghcr.io/filinvadim/warpnet:latest
    hostname: warpnet2
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4002
      - NODE_HOST=207.154.221.44
    volumes:
      - $HOME/storage

  warpnet3:
    container_name: warpnet3
    image: ghcr.io/filinvadim/warpnet:latest
    hostname: warpnet3
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4003
      - NODE_HOST=207.154.221.44
    volumes:
      - $HOME/storage


