services:
  warpnet1:
    image: ghcr.io/filinvadim/warpnet:latest
    hostname: warpnet1
    network_mode: host
    restart: always

  warpnet2:
    image: ghcr.io/filinvadim/warpnet:latest
    hostname: warpnet2
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4002

  warpnet3:
    image: ghcr.io/filinvadim/warpnet:latest
    hostname: warpnet3
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4003

