services:
  warpnet1:
    container_name: warpnet1
    image: ghcr.io/filinvadim/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4001
      - NODE_HOST=${NODE_HOST}
      - NODE_NETWORK=testnet
      - NODE_INMEMORY=false
      - LOGGING_LEVEL=debug
      - NODE_SEED=warpnet1
      - NODE_BOOTSTRAP=/ip4/${NODE_HOST}/tcp/4001/p2p/12D3KooWMKZFrp1BDKg9amtkv5zWnLhuUXN32nhqMvbtMdV2hz7j,/ip4/${NODE_HOST}/tcp/4002/p2p/12D3KooWSjbYrsVoXzJcEtmgJLMVCbPXMzJmNN1JkEZB9LJ2rnmU,/ip4/${NODE_HOST}/tcp/4003/p2p/12D3KooWNXSGyfTuYc3JznW48jay73BtQgHszWfPpyF581EWcpGJ
    volumes:
    - snapshot1:/tmp/snapshot:rw

  warpnet2:
    container_name: warpnet2
    image: ghcr.io/filinvadim/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4002
      - NODE_HOST=${NODE_HOST}
      - NODE_NETWORK=testnet
      - NODE_INMEMORY=false
      - LOGGING_LEVEL=debug
      - NODE_SEED=warpnet2
      - NODE_BOOTSTRAP=/ip4/${NODE_HOST}/tcp/4001/p2p/12D3KooWMKZFrp1BDKg9amtkv5zWnLhuUXN32nhqMvbtMdV2hz7j,/ip4/${NODE_HOST}/tcp/4002/p2p/12D3KooWSjbYrsVoXzJcEtmgJLMVCbPXMzJmNN1JkEZB9LJ2rnmU,/ip4/${NODE_HOST}/tcp/4003/p2p/12D3KooWNXSGyfTuYc3JznW48jay73BtQgHszWfPpyF581EWcpGJ
    volumes:
      - snapshot2:/tmp/snapshot:rw

  warpnet3:
    container_name: warpnet3
    image: ghcr.io/filinvadim/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4003
      - NODE_HOST=${NODE_HOST}
      - NODE_NETWORK=testnet
      - NODE_INMEMORY=false
      - LOGGING_LEVEL=debug
      - NODE_SEED=warpnet3
      - NODE_BOOTSTRAP=/ip4/${NODE_HOST}/tcp/4001/p2p/12D3KooWMKZFrp1BDKg9amtkv5zWnLhuUXN32nhqMvbtMdV2hz7j,/ip4/${NODE_HOST}/tcp/4002/p2p/12D3KooWSjbYrsVoXzJcEtmgJLMVCbPXMzJmNN1JkEZB9LJ2rnmU,/ip4/${NODE_HOST}/tcp/4003/p2p/12D3KooWNXSGyfTuYc3JznW48jay73BtQgHszWfPpyF581EWcpGJ
    volumes:
      - snapshot3:/tmp/snapshot:rw

volumes:
  snapshot1:
  snapshot2:
  snapshot3:
