services:
  warpnet-node1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ID: "1"
    ports:
      - "4001:4001"
    environment:
      NODE_ID: "1"
    networks:
      - warpnet-network

  warpnet-node2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ID: "2"
    ports:
      - "4002:4001"
    environment:
      NODE_ID: "2"
    networks:
      - warpnet-network

  warpnet-node3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ID: "3"
    ports:
      - "4003:4001"
    environment:
      NODE_ID: "3"
    networks:
      - warpnet-network

networks:
  warpnet-network:
    driver: bridge
