services:
  warpnet1:
    image: ghcr.io/filinvadim/warpnet:latest
    ports:
      - "4001:4001"
    networks:
      - warpnet
    restart: always
    environment:
      - DATABASE_DIR=storage
      - NODE_HOST=0.0.0.0
      - NODE_PORT=4001
      - NODE_NETWORK_PREFIX=testnet
      - NODE_BOOTSTRAP=/ip4/67.207.72.168/tcp/4001/p2p/12D3KooWAJHnjq59vsy8h2jtu5tTC7tGS3D5DBdFdogxC5e7nDpg
      - LOGGING_LEVEL=INFO

  warpnet2:
    image: ghcr.io/filinvadim/warpnet:latest
    ports:
      - "4002:4002"
    networks:
      - warpnet
    restart: always
    environment:
      - DATABASE_DIR=storage
      - NODE_HOST=0.0.0.0
      - NODE_PORT=4002
      - NODE_NETWORK_PREFIX=testnet
      - NODE_BOOTSTRAP=/ip4/67.207.72.168/tcp/4001/p2p/12D3KooWAJHnjq59vsy8h2jtu5tTC7tGS3D5DBdFdogxC5e7nDpg
      - LOGGING_LEVEL=INFO

  warpnet3:
    image: ghcr.io/filinvadim/warpnet:latest
    ports:
      - "4003:4003"
    networks:
      - warpnet
    restart: always
    environment:
      - DATABASE_DIR=storage
      - NODE_HOST=0.0.0.0
      - NODE_PORT=4002
      - NODE_NETWORK_PREFIX=testnet
      - NODE_BOOTSTRAP=/ip4/67.207.72.168/tcp/4001/p2p/12D3KooWAJHnjq59vsy8h2jtu5tTC7tGS3D5DBdFdogxC5e7nDpg
      - LOGGING_LEVEL=INFO

networks:
  warpnet:
    driver: bridge
