services:
  warpnet:
    container_name: warpnet
    image: ghcr.io/filinvadim/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4001
      - NODE_HOST=${NODE_HOST}
      - NODE_INMEMORY=false
      - LOGGING_LEVEL=debug
    volumes:
    - snapshot:/tmp/snapshot:rw

volumes:
  snapshot:
