version: 0.0.1
node:
    bootstrap:
      - "/ip4/157.245.23.143/tcp/4001/p2p/12D3KooWJAqBh1FFmFAo6wxSYKYYPuSAzEaoorPx2oiwyuAQxtZu"
      - "/ip4/157.245.23.143/tcp/4002/p2p/12D3KooWJAYu4meUU7v5usd7P4b5LAJjBH6svwmGZqoVe24rLEQo"
      - "/ip4/157.245.23.143/tcp/4003/p2p/12D3KooWLJFqhpSJeMATLuHyHBo6qgAusACGhZLybtwVz3jGGfXy"
    listen_addrs:
      - "/ip4/0.0.0.0/tcp/4001"
      - "/ip4/0.0.0.0/tcp/4002/ws"
      - "/ip6/::/tcp/4001"
database:
    dir: "/storage"
server:
  host: 127.0.0.1
  port: 80
  logging:
    level: info
    format: '{"time":"${time_datetime_only}","method":"${method}","host":"${host}","uri":"${uri}","status":${status},"error":"${error}}'
