package event

const (
	PUBLIC_POST_NODE_VERIFY = "/public/post/admin/verifynode/0.0.0"
	PRIVATE_DELETE_CHAT     = "/private/delete/chat/0.0.0"
	PRIVATE_DELETE_MESSAGE  = "/private/delete/message/0.0.0"
	PRIVATE_DELETE_TWEET    = "/private/delete/tweet/0.0.0"
	PRIVATE_GET_CHAT        = "/private/get/chat/0.0.0"
	PRIVATE_GET_CHATS       = "/private/get/chats/0.0.0"
	PRIVATE_GET_MESSAGE     = "/private/get/message/0.0.0"
	PRIVATE_GET_MESSAGES    = "/private/get/messages/0.0.0"
	PRIVATE_GET_TIMELINE    = "/private/get/timeline/0.0.0"
	PRIVATE_POST_LOGIN      = "/private/post/login/0.0.0"
	PRIVATE_POST_LOGOUT     = "/private/post/logout/0.0.0"
	PRIVATE_POST_PAIR       = "/private/post/pair/0.0.0"
	PRIVATE_POST_TWEET      = "/private/post/tweet/0.0.0"
	PRIVATE_POST_USER       = "/private/post/user/0.0.0"
	PUBLIC_DELETE_REPLY     = "/public/delete/reply/0.0.0"
	PUBLIC_GET_FOLLOWEES    = "/public/get/followees/0.0.0"
	PUBLIC_GET_FOLLOWERS    = "/public/get/followers/0.0.0"
	PUBLIC_GET_INFO         = "/public/get/info/0.0.0"
	PUBLIC_GET_REPLIES      = "/public/get/replies/0.0.0"
	PUBLIC_GET_REPLY        = "/public/get/reply/0.0.0"
	PUBLIC_GET_TWEET        = "/public/get/tweet/0.0.0"
	PUBLIC_GET_TWEET_STATS  = "/public/get/tweetstats/0.0.0"
	PUBLIC_GET_TWEETS       = "/public/get/tweets/0.0.0"
	PUBLIC_GET_USER         = "/public/get/user/0.0.0"
	PUBLIC_GET_USERS        = "/public/get/users/0.0.0"
	PUBLIC_POST_CHAT        = "/public/post/chat/0.0.0"
	PUBLIC_POST_FOLLOW      = "/public/post/follow/0.0.0"
	PUBLIC_POST_LIKE        = "/public/post/like/0.0.0"
	PUBLIC_POST_MESSAGE     = "/public/post/message/0.0.0"
	PUBLIC_POST_REPLY       = "/public/post/reply/0.0.0"
	PUBLIC_POST_RETWEET     = "/public/post/retweet/0.0.0"
	PUBLIC_POST_UNFOLLOW    = "/public/post/unfollow/0.0.0"
	PUBLIC_POST_UNLIKE      = "/public/post/unlike/0.0.0"
	PUBLIC_POST_UNRETWEET   = "/public/post/unretweet/0.0.0"
)
