name: warpnet
services:
  - name: warpnet-service
    github:
      repo: filinvadim/warpnet
      branch: master
    http_port: null
    healthcheck: null
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: SEED_ID
        value: 1