// Package node provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package node

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/filinvadim/dWighter/domain-gen"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// NewEventJSONRequestBody defines body for NewEvent for application/json ContentType.
type NewEventJSONRequestBody = externalRef0.Event

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// NewEventWithBody request with any body
	NewEventWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	NewEvent(ctx context.Context, body NewEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) NewEventWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNewEventRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NewEvent(ctx context.Context, body NewEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNewEventRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewNewEventRequest calls the generic NewEvent builder with application/json body
func NewNewEventRequest(server string, body NewEventJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewNewEventRequestWithBody(server, "application/json", bodyReader)
}

// NewNewEventRequestWithBody generates requests for NewEvent with any type of body
func NewNewEventRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/node/event/new")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// NewEventWithBodyWithResponse request with any body
	NewEventWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NewEventResponse, error)

	NewEventWithResponse(ctx context.Context, body NewEventJSONRequestBody, reqEditors ...RequestEditorFn) (*NewEventResponse, error)
}

type NewEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r NewEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r NewEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// NewEventWithBodyWithResponse request with arbitrary body returning *NewEventResponse
func (c *ClientWithResponses) NewEventWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NewEventResponse, error) {
	rsp, err := c.NewEventWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNewEventResponse(rsp)
}

func (c *ClientWithResponses) NewEventWithResponse(ctx context.Context, body NewEventJSONRequestBody, reqEditors ...RequestEditorFn) (*NewEventResponse, error) {
	rsp, err := c.NewEvent(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNewEventResponse(rsp)
}

// ParseNewEventResponse parses an HTTP response from a NewEventWithResponse call
func ParseNewEventResponse(rsp *http.Response) (*NewEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &NewEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new user
	// (POST /v1/node/event/new)
	NewEvent(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// NewEvent converts echo context to params.
func (w *ServerInterfaceWrapper) NewEvent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.NewEvent(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/v1/node/event/new", wrapper.NewEvent)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYTY/bNhP+KwTf96iNvUm6QHRLmzRYdNEEwQY9BAuDFscWsxSpkCM7xsL/vSApWZJF",
	"r2SjBdKTvoYzzwyf+aCeaKaLUitQaGn6RG2WQ8H87XtjtHm/AYXuqTS6BIMC/LdMc3BX3JVAUyoUwhoM",
	"3Se0AGvZuvvRohFqTff7hBr4XgkDnKZfg4pW/iFp5PXyG2TodJ0wzhkyd9UKPq5o+vWJ/t/Aiqb0f7PW",
	"mVntyeyTUOugaJ88L9lxeEz0T9jebwFwsvQXC9NV/66l1NvputXqjAUfAN9K6dHbySvuRQFSKJi+YHp0",
	"PgBOj86dXgs1WVRXDYaHfULB3S4Cy54ohxWrJNKUlo6eCQVVFY6Y9WOpw1tHCprQdUAZ7rx3nVtLE6rC",
	"Joe7RiBsDE1opQ630rkQrrpqtNTx7aRBkzYJRVGARVaUDvZKm4I51JwhXLlPNBnJtHZ9LwaxjAvM+wzf",
	"K7CRzDPAOJiF4O6hEOoO1Bpzml5HUG+NwGmyR3BbI10lMbRDKg8LVWWsNpFqlFApCoGRIpbQH1drfVW/",
	"rYTCm9dOvrJgbvl4YavlTgDuZ9J/AG+byAOw6L5FTZxtPTkoO4GjLREDGP+Ao3fiEU74N43tTvcFXG+W",
	"Ja2tKLy26g1AlszarTand0GxAqYFx0smrcYTUA5VtVXafj9qX5EScqgtzxXvfiFyYGOWRsk5ZibU6VPq",
	"+431UlcaLWPOjDB81IyTieuuhzVVScmWEmiKpoLkuPIYYAh8wXBqm0loroP7HGxmRIlCK5rS+xzI7SfC",
	"ODdgbWxdSJSDjaoKKTAQswuWodjA0MZfOWAOhmDPFhGWZJUxoFDuSL32oHiptQSmas16q6CbNJ2vkllc",
	"WAAV9+3QT8k2B0UwF7aLYcsscRpa+9OCKRmCynZxmwpwq80jqYUI6oNdoUghpBQWMq24izf8YEXp9vn6",
	"5bxjPXSGJDK0u1g05atv2zGP3L6L4a1K78lgyRf/nuiV3xylOTiIEXSvbuZT4B0VqsPW1fTr0qS7dR2v",
	"POFixaw9GwwbMcty4AsH3z8LhMKO5aDPtDYFmTFs5545WFw0yTIIZI1TrfS0HG9WqDqvxxEdH726vsXi",
	"8hkO1fMn7Yj3cXyZVlhv5wi8S8qdFI9nkMHPFBEyeC2LTFeqb7rhfyGUKNxRZB5LVRO2ZjqMZi8jSBpd",
	"F4OxrqWpDC5Y+i8w6dxxJ9CsoUyMZcet+2c/EH2p54Q+yKUwmDtiT2f6JdnR6wKRMhdCGXrugbnDw+4R",
	"R5tVC386f5rSzeolxl5kydgzTEmhHvujjJHRyqEzdjIwxW5hYAXGMHkmZFfBFxOHqWAC+GK5O3lUqHU9",
	"m1fnFvP6UNFAHdLWLWqaX3+SeCdspjdgduTtp1uy0oYwwoWztawQOLnfCkQwV66iElaWUtRRTigKdCOG",
	"U3Es7pTRhG7A2GDm+sX8xdy31RIUKwVN6Sv/yh2FMPdbMdtcz3gDZ+b/oswUbH2y1X3dpZw3786ibqAP",
	"k0XSnBN+1Xx31KM6mGffbKBHqNtjVb3+rdUPuBvr/QtbamVD8r+cz4eB/fiHc/d17NOt2jApOBGqrDBI",
	"XQ+l3laYkxUTEriT+SWmqd09C2YDhoRfaQ6yrYqCmR1N6W++0BBGFGxJFf6fIVtbx57g44N3Mqiw/m9v",
	"38ydzpgkHDYgdVmAwtocTXwypjRHLG06m7kclG4IS69v3ty8ofuH/d8BAAD//+yOa3z+FgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "./domain.yml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
