// Package node provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package node

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/filinvadim/dWighter/domain-gen"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for NewEventParamsEventType.
const (
	Error            NewEventParamsEventType = "error"
	Follow           NewEventParamsEventType = "follow"
	GetSettingsHosts NewEventParamsEventType = "get_settings_hosts"
	GetTimeline      NewEventParamsEventType = "get_timeline"
	GetTweet         NewEventParamsEventType = "get_tweet"
	GetTweets        NewEventParamsEventType = "get_tweets"
	GetUser          NewEventParamsEventType = "get_user"
	GetUsers         NewEventParamsEventType = "get_users"
	Login            NewEventParamsEventType = "login"
	Logout           NewEventParamsEventType = "logout"
	NewSettingsHosts NewEventParamsEventType = "new_settings_hosts"
	NewTweet         NewEventParamsEventType = "new_tweet"
	NewUser          NewEventParamsEventType = "new_user"
	Ping             NewEventParamsEventType = "ping"
	Pong             NewEventParamsEventType = "pong"
	Unfollow         NewEventParamsEventType = "unfollow"
)

// NewEventParamsEventType defines parameters for NewEvent.
type NewEventParamsEventType string

// NewEventJSONRequestBody defines body for NewEvent for application/json ContentType.
type NewEventJSONRequestBody = externalRef0.Event

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// NewEventWithBody request with any body
	NewEventWithBody(ctx context.Context, eventType NewEventParamsEventType, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	NewEvent(ctx context.Context, eventType NewEventParamsEventType, body NewEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) NewEventWithBody(ctx context.Context, eventType NewEventParamsEventType, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNewEventRequestWithBody(c.Server, eventType, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NewEvent(ctx context.Context, eventType NewEventParamsEventType, body NewEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNewEventRequest(c.Server, eventType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewNewEventRequest calls the generic NewEvent builder with application/json body
func NewNewEventRequest(server string, eventType NewEventParamsEventType, body NewEventJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewNewEventRequestWithBody(server, eventType, "application/json", bodyReader)
}

// NewNewEventRequestWithBody generates requests for NewEvent with any type of body
func NewNewEventRequestWithBody(server string, eventType NewEventParamsEventType, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "event_type", runtime.ParamLocationPath, eventType)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/node/event/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// NewEventWithBodyWithResponse request with any body
	NewEventWithBodyWithResponse(ctx context.Context, eventType NewEventParamsEventType, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NewEventResponse, error)

	NewEventWithResponse(ctx context.Context, eventType NewEventParamsEventType, body NewEventJSONRequestBody, reqEditors ...RequestEditorFn) (*NewEventResponse, error)
}

type NewEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r NewEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r NewEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// NewEventWithBodyWithResponse request with arbitrary body returning *NewEventResponse
func (c *ClientWithResponses) NewEventWithBodyWithResponse(ctx context.Context, eventType NewEventParamsEventType, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NewEventResponse, error) {
	rsp, err := c.NewEventWithBody(ctx, eventType, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNewEventResponse(rsp)
}

func (c *ClientWithResponses) NewEventWithResponse(ctx context.Context, eventType NewEventParamsEventType, body NewEventJSONRequestBody, reqEditors ...RequestEditorFn) (*NewEventResponse, error) {
	rsp, err := c.NewEvent(ctx, eventType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNewEventResponse(rsp)
}

// ParseNewEventResponse parses an HTTP response from a NewEventWithResponse call
func ParseNewEventResponse(rsp *http.Response) (*NewEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &NewEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new user
	// (POST /v1/node/event/{event_type})
	NewEvent(ctx echo.Context, eventType NewEventParamsEventType) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// NewEvent converts echo context to params.
func (w *ServerInterfaceWrapper) NewEvent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "event_type" -------------
	var eventType NewEventParamsEventType

	err = runtime.BindStyledParameterWithOptions("simple", "event_type", ctx.Param("event_type"), &eventType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter event_type: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.NewEvent(ctx, eventType)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/v1/node/event/:event_type", wrapper.NewEvent)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZX2/bNhD/KgS3R6VO2i5A9datXRcsaIsuxR4CQ2Cks82GIlWSsmoE/u7DkZIlWYws",
	"ZSuwPkmh7s/v/vOcB5qqvFASpDU0fqAm3UDO3GumcsZl8lZrpd9uQVo8LLQqQFsOjiRVGeDT7gqgMeXS",
	"who03Uc0B2PYuvvRWM3lmu73EdXwteQaMhrfehEt/TJq6NXdF0gtymqAhDFkzDJ8Mrn7sKLx7QP9WcOK",
	"xvSnRWvaorZrUcv6yOXay9tHkxg6XpjI8R6qmwrAzmX6bGC2ot+VEKqarUmu5vO9A/taCGeZmct4w3MQ",
	"XMJsvtl+fAd2th+9Zcg2z7BrteZyLocqZxv0F1jL5dr8ocxM17+HKsS83EfU8hyMZXmBJbRSOmeWxlhT",
	"cIafaHSifFv+kcr16fkJvpZgAhWsgWWgE57hHzmX1yDXdkPji4HyiFaa22m0R0BbJV0hI6CHiT5sf6U2",
	"Sgd6XEQFz7kNtMaIfjtbq7P6tOTSXr5E+tKAvspOt8ua7iTuThrPgc1N4nsCdLHcKSWAyR4BMgQp5lm+",
	"HzUkkLXfLwjjUPq964dJhU7rHGC2+C2oaTaI6CBsHE7blAdo/juzr/k9PGLttCaDKp7QYhq2qNU1hrId",
	"GwOsBTOmUvrx0EiWwzRXOcqolTiO6DCWWtkDsqP7RqCdH/r8hNnUnw1jRRieYgP1G/yGL9xCboIerA+Y",
	"1mw3cJrnX47iOFlVE413ck4Z3b+m/Ut3N8ImOvxEvU5ViqSjmuo9QpZCsDsBNLa6hOi4x2pgFrKE2amX",
	"lchF020JYFLNC8uVpDG92QC5+khYlmkwJsTnq/+goyx9XQfmJUst38JQx98bsBvQxPZ0EW5IWmoN0ood",
	"qXmj8KBVlXxsDAtmbGIAZNi2w62MVBuQxG646WKomCEoodU/zZmCWZDpLqxTgq2Uvic1EbHqoJdLknMh",
	"uIFUyQz9Dd9YXmCcL56fd7T7GRgF9kn0RdOT+7oxD8nVmxDesnCWDFg+u3OiVi44UmWAEAPoXlyeT4F3",
	"1EEOoavTr5sm3dB1rHIJN9Jz2n11uP+CsUmT5gMXoHH9bjhlX8ByHPTJA1y5UrMKv2GUdZVPRnDkV2/L",
	"iJc+waH5/r9n/00YZqqkrWN8AuVTWqHg9/NTwd2lAqnghCWpKmUfQVMiOZc8L3Man4eqWftAzUbTBDgA",
	"qBH5ZEzfIUfm3tV8AjVZMJI/x1P8B1mpP9dXhj7WO67tBjN3eio/Jf17IyDQKbt779SrY8uVSEyshymj",
	"rGbR5kmatJmhSnB537/HaBFsDSpljzom3yUaVqA1EzMhY8NOJt6kvArIkrvdo1tPLWu0yuY27Xo/aqAO",
	"sxeZmpHXv0a84SZVW9A78vrjFVkpTRjJOOq6Ky1k5Kbi1oI+w15JWFEIXns5opZbvF+giGNyFEYjugVt",
	"vJqLZ+fPzt0ULUCygtOYvnBHuNXZjQvFYnuxQBMWgJeExYN7JGjJ3hVcfT3AsnMQcNGm76HeKVCQZjlY",
	"l5S3D5SjXhSOnnGOpa1E2nWiv6f7No0awCXnLS3Q3xEtlHuA1krTiK7BJm5vaF9N/e4be+cdP0ioGnp8",
	"bWh8KdCIlvLwKnCd9k9VHgTVP9rUf5p6fUz8jueFHh0uh0mzjJol61eV7Y4GdSeuiy/Gl1Drjin/WfA/",
	"xvZzE93qDkyhpPF98vn5+TAHP/yJmfEy9OlKbpngGeGyKK2nuhhSvS7thqwYF5AhzS8hSW2iG9Bb0MTH",
	"EyGbMs+Z3tGY/uZ6MmFEQkXqoFm2xoSi3salM9KL8HnWV3OtUiZIBlsQqshB2lodBloLGtONtUW8WGC3",
	"Ehit+OLy1eUrul/u/wkAAP//Bq9RM8caAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./domain.yml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
