openapi: 3.0.0
info:
  title: Distributed Twitter API
  version: 1.0.0
  description: Discovery API for a distributed Twitter-like application
servers:
  - url: https://localhost:16969
    description: Local development server

paths:
  /v1/discovery/event/new:
    post:
      tags:
        - Event
      summary: Create a new user
      operationId: newEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Invalid input
        '401':
          description: Auth failed
        '500':
          description: Discovery server error

components:
  schemas:
    Event:
      type: object
      properties:
        event_type:
          type: string
          enum: [ ping,pong,error,user,tweet,follow,unfollow ]
          default: ping
        timestamp:
          type: string
          format: date-time
        data:
          oneOf:
            - $ref: '#/components/schemas/PingEvent'
            - $ref: '#/components/schemas/ErrorEvent'
            - $ref: '#/components/schemas/NewTweetEvent'
            - $ref: '#/components/schemas/NewUserEvent'
            - $ref: '#/components/schemas/NewFollowEvent'
            - $ref: '#/components/schemas/NewUnfollowEvent'
      required:
        - timestamp
        - event_type

    PingEvent:
      type: object
      properties:
        owner_node:
          $ref: './components.yml#/components/schemas/Node'
        owner_info:
          $ref: './components.yml#/components/schemas/User'
        dest_ip:
          type: string
        cached_nodes:
          type: array
          items:
            $ref: './components.yml#/components/schemas/Node'
      required:
        - owner_node
        - owner_info
        - cached_nodes

    PongEvent:
      $ref: '#/components/schemas/PingEvent'

    ErrorEvent:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message

    NewTweetEvent:
      type: object
      properties:
        tweet:
          $ref: './components.yml#/components/schemas/Tweet'
      required:
        - tweet

    NewUserEvent:
      type: object
      properties:
        user:
          $ref: './components.yml#/components/schemas/User'
      required:
        - user

    NewFollowEvent:
      type: object
      properties:
        request:
          $ref: './components.yml#/components/schemas/FollowRequest'
      required:
        - request

    NewUnfollowEvent:
      type: object
      properties:
        request:
          $ref: './components.yml#/components/schemas/UnfollowRequest'
      required:
        - request
