openapi: 3.0.0
info:
  title: Warp Network
  version: 1.0.0
  description: Components for a distributed Twitter-like application

paths: {}

components:
  schemas:
    Owner:
      type: object
      properties:
        id:
          type: string
        node_id:
          type: string
        username:
          type: string
          minLength: 1
        description:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - username
        - description
        - node_id
        - created_at

    User:
      type: object
      properties:
        id:
          type: string
        node_id:
          type: string
        username:
          type: string
          minLength: 1
        description:
          type: string
        followers_num:
          type: integer
          format: int64
        followed_num:
          type: integer
          format: int64
        link:
          type: string
          format: url
        location:
          type: string
        birthdate:
          type: string
          format: date-time
        followers:
          type: array
          items:
            type: string
        followed:
          type: array
          items:
            type: string
        referred_by:
          type: string
        my_referrals:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - description
        - username
        - node_id
        - followed_num
        - followers_num
        - followed
        - followers
        - created_at

    Tweet:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        username:
          type: string
        id:
          type: string
        content:
          type: string
          minLength: 1
        created_at:
          type: string
          format: date-time
        likes_count:
          type: integer
          format: int64
          minimum: 0
        retweets_count:
          type: integer
          format: int64
          minimum: 0
        likes:
          type: array
          items:
            $ref: '#/components/schemas/Like'
        retweets:
          type: array
          items:
            $ref: '#/components/schemas/Retweet'
        parent_id:
          type: string
        root_id:
          type: string
      required:
        - user_id
        - id
        - content
        - parent_id
        - root_id
        - username
        - created_at

    ChatMessage:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        username:
          type: string
        id:
          type: string
        chat_id:
          type: string
        content:
          type: string
          minLength: 1
        created_at:
          type: string
          format: date-time
      required:
        - user_id
        - chat_id
        - id
        - content
        - username
        - created_at

    Chat:
      type: object
      properties:
        id:
          type: string
        from_user_id:
          type: string
        to_user_id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - from_user_id
        - to_user_id
        - created_at
        - updated_at

    Like:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        tweet_id:
          type: string
          minLength: 1
      required:
        - user_id
        - tweet_id

    Retweet:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        tweet_id:
          type: string
          minLength: 1
      required:
        - user_id
        - tweet_id

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message

    ReplyNode:
      type: object
      properties:
        reply:
          $ref: '#/components/schemas/Tweet'
        children:
          type: array
          items:
            $ref: '#/components/schemas/ReplyNode'
      required:
        - reply
        - children




