openapi: 3.0.0
info:
  title: Distributed Twitter API
  version: 1.0.0
  description: Components for a distributed Twitter-like application

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        node_id:
          type: string
          format: uuid
        username:
          type: string
          minLength: 1
        description:
          type: string
        followers_num:
          type: integer
          format: int64
        followed_num:
          type: integer
          format: int64
        link:
          type: string
          format: url
        location:
          type: string
        birthdate:
          type: string
          format: date-time
        followers:
          type: array
          items:
            type: string
        followed:
          type: array
          items:
            type: string
        referred_by:
          type: string
        my_referrals:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - username
        - description
        - username
        - node_id
        - followed_num
        - followers_num
        - followed
        - followers
        - created_at

    Tweet:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        username:
          type: string
        id:
          type: string
        content:
          type: string
          minLength: 1
        created_at:
          type: string
          format: date-time
        likes_count:
          type: integer
          format: int64
          minimum: 0
        retweets_count:
          type: integer
          format: int64
          minimum: 0
        likes:
          type: array
          items:
            $ref: '#/components/schemas/Like'
        retweets:
          type: array
          items:
            $ref: '#/components/schemas/Retweet'
        parent_id:
          type: string
        root_id:
          type: string
      required:
        - user_id
        - id
        - content
        - parent_id
        - root_id
        - username
        - created_at

    ChatMessage:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        username:
          type: string
        id:
          type: string
        chat_id:
          type: string
        content:
          type: string
          minLength: 1
        created_at:
          type: string
          format: date-time
      required:
        - user_id
        - chat_id
        - id
        - content
        - username
        - created_at

    Chat:
      type: object
      properties:
        id:
          type: string
        from_user_id:
          type: string
        to_user_id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - from_user_id
        - to_user_id
        - created_at
        - updated_at

    Like:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        tweet_id:
          type: string
          minLength: 1
      required:
        - user_id
        - tweet_id

    Retweet:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        tweet_id:
          type: string
          minLength: 1
      required:
        - user_id
        - tweet_id

    AddSettingRequest:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/SettingNameEnum'
        value:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - name
        - value

    CreateChatRequest:
      type: object
      properties:
        from_user_id:
          type: string
          minLength: 1
        to_user_id:
          type: string
          minLength: 1
      required:
        - from_user_id
        - to_user_id

    FollowRequest:
      type: object
      properties:
        reader_id:
          type: string
          minLength: 1
        writer_id:
          type: string
          minLength: 1
      required:
        - reader_id
        - writer_id

    UnfollowRequest:
      type: object
      properties:
        reader_id:
          type: string
          minLength: 1
        writer_id:
          type: string
          minLength: 1
      required:
        - reader_id
        - writer_id

    Node:
      type: object
      nullable: true
      properties:
        id:
          type: string
          format: uuid
        host:
          type: string
          description: The IP address
        is_active:
          type: boolean
          description: Whether the IP address is currently active
        latency:
          type: integer
          format: int64
          description: The network latency to this IP in milliseconds
          example: 120
        last_seen:
          type: string
          format: date-time
          description: The timestamp when this IP address was last active
        uptime:
          type: integer
          format: int64
          description: Uptime of the node in seconds
          example: 3600
        created_at:
          type: string
          format: date-time
        owner_id:
          type: string
          description: user ID
        is_owned:
          type: boolean
      required:
        - is_owned
        - host
        - is_active
        - last_seen
        - owner_id
        - id
        - created_at

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message

    RepliesTreeResponse:
      type: object
      properties:
        user_id:
          type: string
        cursor:
          type: string
        replies:
          type: array
          items:
            $ref: '#/components/schemas/ReplyNode'
      required:
        - cursor
        - replies

    ReplyNode:
      type: object
      properties:
        reply:
          $ref: '#/components/schemas/Tweet'
        children:
          type: array
          items:
            $ref: '#/components/schemas/ReplyNode'
      required:
        - reply
        - children

    TweetsResponse:
      type: object
      properties:
        user_id:
          type: string
        cursor:
          type: string
        tweets:
          type: array
          items:
            $ref: '#/components/schemas/Tweet'
      required:
        - cursor
        - tweets

    ChatsResponse:
      type: object
      properties:
        user_id:
          type: string
        cursor:
          type: string
        chats:
          type: array
          items:
            $ref: '#/components/schemas/Chat'
      required:
        - cursor
        - chats

    MessagesResponse:
      type: object
      properties:
        user_id:
          type: string
        cursor:
          type: string
        messages:
          type: array
          items:
            $ref: '#/components/schemas/ChatMessage'
      required:
        - cursor
        - messages

    UsersResponse:
      type: object
      properties:
        cursor:
          type: string
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
      required:
        - cursor
        - users

    HostsResponse:
      type: object
      properties:
        user_id:
          type: string
        cursor:
          type: string
        hosts:
          type: array
          items:
            type: string
      required:
        - cursor
        - hosts

    LoginResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: '#/components/schemas/User'
      required:
        - token
        - user

    AuthRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    SettingNameEnum:
      type: string
      enum: [node_addresses]
      default: node_addresses

    Event:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        data:
          anyOf:
            - $ref: '#/components/schemas/PingEvent'
            - $ref: '#/components/schemas/ErrorEvent'
            - $ref: '#/components/schemas/NewTweetEvent'
            - $ref: '#/components/schemas/NewUserEvent'
            - $ref: '#/components/schemas/NewFollowEvent'
            - $ref: '#/components/schemas/NewUnfollowEvent'
            - $ref: '#/components/schemas/GetAllTweetsEvent'
            - $ref: '#/components/schemas/GetTimelineEvent'
            - $ref: '#/components/schemas/GetTweetEvent'
            - $ref: '#/components/schemas/GetUserEvent'
            - $ref: '#/components/schemas/GetAllUsersEvent'
            - $ref: '#/components/schemas/LoginEvent'
            - $ref: '#/components/schemas/LogoutEvent'
            - $ref: '#/components/schemas/GetSettingsHostsEvent'
            - $ref: '#/components/schemas/NewSettingsHostsEvent'
            - $ref: '#/components/schemas/GetRepliesEvent'
            - $ref: '#/components/schemas/NewReplyEvent'
            - $ref: '#/components/schemas/GetReplyEvent'
      required:
        - timestamp

    PingEvent:
      type: object
      properties:
        owner_node:
          $ref: '#/components/schemas/Node'
        owner_info:
          $ref: '#/components/schemas/User'
        dest_host:
          type: string
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
      required:
        - nodes

    PongEvent:
      $ref: '#/components/schemas/PingEvent'

    LoginEvent:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    LogoutEvent:
      type: object

    ErrorEvent:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message

    NewReplyEvent:
      type: object
      properties:
        tweet:
          $ref: '#/components/schemas/Tweet'

    GetRepliesEvent:
      type: object
      properties:
        parent_reply_id:
          type: string
        root_id:
          type: string
        limit:
          type: integer
          x-go-type: uint64
        cursor:
          type: string
      required:
        - root_id
        - parent_reply_id

    GetReplyEvent:
      type: object
      properties:
        parent_reply_id:
          type: string
        root_id:
          type: string
        reply_id:
          type: string
      required:
        - root_id
        - parent_reply_id
        - reply_id

    NewTweetEvent:
      type: object
      properties:
        tweet:
          $ref: '#/components/schemas/Tweet'

    GetTweetEvent:
      type: object
      properties:
        userId:
          type: string
        tweetId:
          type: string
      required:
        - userId
        - tweetId

    GetTimelineEvent:
      $ref: '#/components/schemas/GetAllTweetsEvent'

    GetAllUsersEvent:
      type: object
      properties:
        limit:
          type: integer
          x-go-type: uint64
        cursor:
          type: string
        is_following:
          type: boolean
        is_followed:
          type: boolean

    GetSettingsHostsEvent:
      type: object
      properties:
        limit:
          type: integer
          x-go-type: uint64
        cursor:
          type: string

    NewSettingsHostsEvent:
      type: object
      properties:
        hosts:
          type: array
          items:
            type: string
      required:
        - hosts

    GetAllTweetsEvent:
      type: object
      properties:
        userId:
          type: string
        limit:
          type: integer
          x-go-type: uint64
        cursor:
          type: string
      required:
        - userId

    NewUserEvent:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'

    GetUserEvent:
      type: object
      properties:
        userId:
          type: string
      required:
        - userId

    NewFollowEvent:
      type: object
      properties:
        request:
          $ref: '#/components/schemas/FollowRequest'

    NewUnfollowEvent:
      type: object
      properties:
        request:
          $ref: '#/components/schemas/UnfollowRequest'
