openapi: 3.0.0
info:
  title: Distributed Twitter API
  version: 1.0.0
  description: Components for a distributed Twitter-like application

components:
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: string
        node_id:
          type: string
          format: uuid
        username:
          type: string
          minLength: 1
        description:
          type: string
        followers_num:
          type: integer
          format: int64
        followed_num:
          type: integer
          format: int64
        link:
          type: string
          format: url
        location:
          type: string
        birthdate:
          type: string
          format: date-time
        followers:
          type: array
          items:
            type: string
        followed:
          type: array
          items:
            type: string
        referred_by:
          type: string
        my_referrals:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
      required:
        - username
        - node_id

    Tweet:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        username:
          type: string
        tweet_id:
          type: string
          minLength: 1
        content:
          type: string
          minLength: 1
        sequence:
          type: integer
          format: int64
          minimum: 0
        created_at:
          type: string
          format: date-time
        likes_count:
          type: integer
          format: int64
          minimum: 0
        retweets_count:
          type: integer
          format: int64
          minimum: 0
        likes:
          type: array
          items:
            $ref: '#/components/schemas/Like'
        retweets:
          type: array
          items:
            $ref: '#/components/schemas/Retweet'
      required:
        - user_id
        - content

    Like:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        tweet_id:
          type: string
          minLength: 1
      required:
        - user_id
        - tweet_id

    Retweet:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        tweet_id:
          type: string
          minLength: 1
      required:
        - user_id
        - tweet_id

    FollowRequest:
      type: object
      properties:
        reader_id:
          type: string
          minLength: 1
        writer_id:
          type: string
          minLength: 1
      required:
        - reader_id
        - writer_id

    UnfollowRequest:
      type: object
      properties:
        reader_id:
          type: string
          minLength: 1
        writer_id:
          type: string
          minLength: 1
      required:
        - reader_id
        - writer_id

    Node:
      type: object
      nullable: true
      properties:
        id:
          type: string
          format: uuid
        host:
          type: string
          description: The IP address
        is_active:
          type: boolean
          description: Whether the IP address is currently active
        latency:
          type: integer
          format: int64
          description: The network latency to this IP in milliseconds
          example: 120
        last_seen:
          type: string
          format: date-time
          description: The timestamp when this IP address was last active
        uptime:
          type: integer
          format: int64
          description: Uptime of the node in seconds
          example: 3600
        created_at:
          type: string
          format: date-time
        owner_id:
          type: string
          description: user ID
        is_owned:
          type: boolean
      required:
        - is_owned
        - host
        - is_active
        - last_seen
        - owner_id
        - id

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message

    TweetsResponse:
      type: object
      properties:
        cursor:
          type: string
        tweets:
          type: array
          items:
            $ref: '#/components/schemas/Tweet'
      required:
        - cursor
        - tweets

    UsersResponse:
      type: object
      properties:
        cursor:
          type: string
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
      required:
        - cursor
        - users

    HostsResponse:
      type: object
      properties:
        cursor:
          type: string
        hosts:
          type: array
          items:
            type: string
      required:
        - cursor
        - hosts

    LoginResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: '#/components/schemas/User'
      required:
        - token
        - user

    AuthRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    SettingNameEnum:
      type: string
      enum: [node_addresses]
      default: node_addresses

    AddSettingRequest:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/SettingNameEnum'
        value:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - name
        - value

    Event:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        data:
          anyOf:
            - $ref: '#/components/schemas/PingEvent'
            - $ref: '#/components/schemas/ErrorEvent'
            - $ref: '#/components/schemas/NewTweetEvent'
            - $ref: '#/components/schemas/NewUserEvent'
            - $ref: '#/components/schemas/NewFollowEvent'
            - $ref: '#/components/schemas/NewUnfollowEvent'
            - $ref: '#/components/schemas/GetAllTweetsEvent'
            - $ref: '#/components/schemas/GetTimelineEvent'
            - $ref: '#/components/schemas/GetTweetEvent'
            - $ref: '#/components/schemas/GetUserEvent'
            - $ref: '#/components/schemas/GetAllUsersEvent'
            - $ref: '#/components/schemas/LoginEvent'
            - $ref: '#/components/schemas/LogoutEvent'
            - $ref: '#/components/schemas/GetSettingsHostsEvent'
            - $ref: '#/components/schemas/NewSettingsHostsEvent'
      required:
        - timestamp

    PingEvent:
      type: object
      properties:
        owner_node:
          $ref: '#/components/schemas/Node'
        owner_info:
          $ref: '#/components/schemas/User'
        dest_host:
          type: string
        cached_nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
      required:
        - cached_nodes

    PongEvent:
      $ref: '#/components/schemas/PingEvent'

    LoginEvent:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    LogoutEvent:
      type: object

    ErrorEvent:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message

    NewTweetEvent:
      type: object
      properties:
        tweet:
          $ref: '#/components/schemas/Tweet'

    GetTweetEvent:
      type: object
      properties:
        userId:
          type: string
        tweetId:
          type: string
      required:
        - userId
        - tweetId

    GetTimelineEvent:
      $ref: '#/components/schemas/GetAllTweetsEvent'

    GetAllUsersEvent:
      type: object
      properties:
        limit:
          type: integer
          x-go-type: uint64
        cursor:
          type: string
        is_following:
          type: boolean
        is_followed:
          type: boolean

    GetSettingsHostsEvent:
      type: object
      properties:
        limit:
          type: integer
          x-go-type: uint64
        cursor:
          type: string

    NewSettingsHostsEvent:
      type: object
      properties:
        hosts:
          type: array
          items:
            type: string
      required:
        - hosts

    GetAllTweetsEvent:
      type: object
      properties:
        userId:
          type: string
        limit:
          type: integer
          x-go-type: uint64
        cursor:
          type: string
      required:
        - userId

    NewUserEvent:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'

    GetUserEvent:
      type: object
      properties:
        userId:
          type: string
      required:
        - userId

    NewFollowEvent:
      type: object
      properties:
        request:
          $ref: '#/components/schemas/FollowRequest'

    NewUnfollowEvent:
      type: object
      properties:
        request:
          $ref: '#/components/schemas/UnfollowRequest'
