openapi: 3.0.0
info:
  title: Warp Network
  version: 1.0.0
  description: Components for a distributed Twitter-like application

paths: {}

components:
  schemas:
    AuthNodeInfo:
      type: object
      properties:
        identity:
          $ref: '#/components/schemas/Identity'
        version:
          type: string
      required:
        - identity
        - version

    Identity:
      type: object
      properties:
        token:
          type: string
        owner:
          $ref: '#/components/schemas/Owner'
      required:
        - token
        - owner

    Owner:
      type: object
      properties:
        user_id:
          type: string
        username:
          type: string
        node_id:
          type: string
        ipv4:
          type: string
        ipv6:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - user_id
        - username
        - node_id
        - ipv4
        - ipv6
        - created_at
        
    User:
      type: object
      properties:
        id:
          type: string
        node_id:
          type: string
        username:
          type: string
          minLength: 1
        bio:
          type: string
        avatar:
          type: string
          description: mime type + "," + base64
        background_image:
          type: string
          description: mime type + "," + base64
        tweets_count:
          type: integer
          x-go-type: uint64
        followers_count:
          type: integer
          x-go-type: uint64
        followees_count:
          type: integer
          x-go-type: uint64
        website:
          type: string
          format: hostname
        rtt:
          type: integer
          format: int64
          default: 9223372036854775807
          description: round trip time - nanoseconds, default - max int64
        birthdate:
          type: string
          format: date
        created_at:
          type: string
          format: date-time
      required:
        - id
        - bio
        - username
        - node_id
        - followers_count
        - followees_count
        - created_at
        - tweets_count
        - birthdate
        - rtt

    Tweet:
      type: object
      properties:
        user_id:
          type: string
        username:
          type: string
        id:
          type: string
        text:
          type: string
          minLength: 1
        created_at:
          type: string
          format: date-time
        parent_id:
          type: string
        root_id:
          type: string
        retweet_id:
          type: string
      required:
        - user_id
        - id
        - text
        - content
        - parent_id
        - root_id
        - username
        - created_at

    ChatMessage:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        username:
          type: string
        id:
          type: string
        chat_id:
          type: string
        content:
          type: string
          minLength: 1
        created_at:
          type: string
          format: date-time
      required:
        - user_id
        - chat_id
        - id
        - content
        - username
        - created_at

    Chat:
      type: object
      properties:
        id:
          type: string
        from_user_id:
          type: string
        to_user_id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - from_user_id
        - to_user_id
        - created_at
        - updated_at

    Like:
      type: object
      properties:
        user_id:
          type: string
          minLength: 1
        tweet_id:
          type: string
          minLength: 1
      required:
        - user_id
        - tweet_id

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message

    ReplyNode:
      type: object
      properties:
        reply:
          $ref: '#/components/schemas/Tweet'
        children:
          type: array
          items:
            $ref: '#/components/schemas/ReplyNode'
      required:
        - reply
        - children


    Following:
      type: object
      properties:
        followee:
          type: string
          description: to user
        follower:
          type: string
          description: from user
        follower_username:
          type: string
      required:
        - followee
        - follower


