openapi: 3.0.0
info:
  title: Warp net front face
  version: 1.0.0
  description: Extrenal API for a distributed Twitter-like application
servers:
  - url: http://localhost:4002
    description: Interface address

paths:
  /:
    get:
      summary: Serve static files
      operationId: GetIndex
      responses:
        '200':
          description: OK

  /{file*}:
    get:
      summary: Serve static files
      operationId: GetStaticFile
      description: Returns any static file from the /static/ directory
      parameters:
        - in: path
          name: file
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Static file served successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: File not found

  /v1/api/ws:
    get:
      summary: Serve Websocket connection
      operationId: WebsocketUpgrade
      responses:
        '101':
          description: Upgraded
        '500':
          description: Internal server error

components:
  schemas:
    WebsocketMessage:
      type: object
      properties:
        event_type:
          type: string
        message_id:
          type: string
      required:
        - message_id
        - event_type

    LoginResponse:
      type: object
      properties:
        message_id:
          type: string
        token:
          type: string
        user:
          $ref: '#/components/schemas/Owner'
      required:
        - token
        - user
        - message_id

    Owner:
      $ref: './domain.yml#/components/schemas/User'

    ErrorResponse:
      type: object
      properties:
        message_id:
          type: string
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message