openapi: 3.0.0
info:
  title: Distributed Twitter API
  version: 1.0.0
  description: Extrenal API for a distributed Twitter-like application
servers:
  - url: http://localhost:6969
    description: Local development server

paths:
  /:
    get:
      summary: Serve the main index.html page
      description: This endpoint serves the main frontend page of the application (index.html).
      operationId: GetIndex
      responses:
        '200':
          description: The main HTML page of the application
          content:
            text/html:
              schema:
                type: string
                example: "<html><head><title>Twitter Clone</title></head><body>Welcome to Twitter Clone</body></html>"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: Internal Server Error

  /v1/api/auth/login:
    post:
      tags:
        - Auth
      summary: Store credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './domain.yml#/components/schemas/AuthRequest'
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: './domain.yml#/components/schemas/User'
        '401':
          description: Auth failed
        '500':
          description: Internal server error

  /v1/api/auth/logout:
    post:
      tags:
        - Auth
      parameters:
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      summary: Close service
      responses:
        '200':
          description: Success
        '500':
          description: Internal server error

  /v1/api/users:
    get:
      tags:
        - User
      summary: Get users list
      parameters:
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
        - name: cursor
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            x-go-type: uint64
            default: 20
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: './domain.yml#/components/schemas/UsersResponse'
        '404':
          description: User not found
    post:
      tags:
        - User
      summary: Create a new user
      parameters:
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './domain.yml#/components/schemas/User'
      responses:
        '200':
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: './domain.yml#/components/schemas/User'
        '400':
          description: Invalid input

  /v1/api/users/{user_id}:
    get:
      tags:
        - User
      summary: Get user information
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: './domain.yml#/components/schemas/User'
        '404':
          description: User not found

  /v1/api/tweets:
    post:
      tags:
        - Tweet
      summary: Publish a new tweet
      parameters:
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './domain.yml#/components/schemas/Tweet'
      responses:
        '200':
          description: Tweet successfully created
          content:
            application/json:
              schema:
                $ref: './domain.yml#/components/schemas/Tweet'
        '400':
          description: Invalid input

  /v1/api/tweets/replies:
    post:
      tags:
        - Reply
      summary: Publish a new reply to tweet
      parameters:
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './domain.yml#/components/schemas/Tweet'
      responses:
        '200':
          description: Reply successfully created
          content:
            application/json:
              schema:
                $ref: './domain.yml#/components/schemas/Tweet'
        '400':
          description: Invalid input

  /v1/api/tweets/replies/{root_tweet_id}/{tweet_id}:
    get:
      tags:
        - Reply
      summary: Get a certain reply
      parameters:
        - name: root_tweet_id
          in: path
          required: true
          schema:
            type: string
        - name: tweet_id
          in: path
          required: true
          schema:
            type: string
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reply successfully fetched
        '400':
          description: Invalid input

  /v1/api/tweets/replies/{root_tweet_id}/{parent_tweet_id}:
    get:
      tags:
        - Reply
      summary: Get all tweet's replies
      parameters:
        - name: cursor
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            x-go-type: uint64
            default: 20
        - name: parent_tweet_id
          in: path
          required: true
          schema:
            type: string
        - name: root_tweet_id
          in: path
          required: true
          schema:
            type: string
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reply successfully fetched
        '400':
          description: Invalid input

  /v1/api/tweets/{user_id}/{tweet_id}:
    get:
      tags:
        - Tweet
      summary: Get a certain tweet
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: tweet_id
          in: path
          required: true
          schema:
            type: string
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tweet successfully fetched
        '400':
          description: Invalid input

  /v1/api/tweets/{user_id}:
    get:
      tags:
        - Tweet
      summary: Get user's tweets
      parameters:
        - name: cursor
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            x-go-type: uint64
            default: 20
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of user's tweets
          content:
            application/json:
              schema:
                $ref: './domain.yml#/components/schemas/TweetsResponse'
        '404':
          description: User or tweets not found

  /v1/api/tweets/timeline/{user_id}:
    get:
      tags:
        - Tweet
      summary: Get user's tweet timeline
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: cursor
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            x-go-type: uint64
            default: 20
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User's tweet timeline
          content:
            application/json:
              schema:
                $ref: './domain.yml#/components/schemas/TweetsResponse'
        '404':
          description: User or timeline not found

  /v1/api/users/follow:
    post:
      tags:
        - User
      summary: Follow another user
      parameters:
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './domain.yml#/components/schemas/FollowRequest'
      responses:
        '201':
          description: Successfully followed the user
        '400':
          description: Invalid input

  /v1/api/users/unfollow:
    post:
      tags:
        - User
      summary: Unfollow a user
      parameters:
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './domain.yml#/components/schemas/UnfollowRequest'
      responses:
        '200':
          description: Successfully unfollowed the user
        '400':
          description: Invalid input

  /v1/api/nodes/settings:
    post:
      tags:
        - Setting
      summary: Add setting
      parameters:
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './domain.yml#/components/schemas/AddSettingRequest'
      responses:
        '200':
          description: Success
        '400':
          description: Invalid input
    get:
      tags:
        - Setting
      summary: Add setting
      parameters:
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
        - name: cursor
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            x-go-type: uint64
            default: 20
        - in: query
          name: name
          required: true
          schema:
            $ref: './domain.yml#/components/schemas/SettingNameEnum'
      responses:
        '200':
          description: Success
        '400':
          description: Invalid input

