openapi: 3.0.0
info:
  title: Warp net front face
  version: 1.0.0
  description: Extrenal API for a distributed Twitter-like application
servers:
  - url: http://localhost:6969
    description: Interface address

paths:
  /:
    get:
      summary: Serve static files
      operationId: GetIndex
      responses:
        '200':
          description: OK

  /{file*}:
    get:
      summary: Serve static files
      operationId: GetStaticFile
      description: Returns any static file from the /static/ directory
      parameters:
        - in: path
          name: file
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Static file served successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: File not found

  /v1/api/auth/login:
    post:
      tags:
        - Auth
      summary: Store credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: './domain.yml#/components/schemas/Owner'
        '401':
          description: Auth failed
        '500':
          description: Internal handler error

  /v1/api/auth/logout:
    post:
      tags:
        - Auth
      parameters:
        - in: header
          name: X-SESSION-TOKEN
          required: true
          schema:
            type: string
      summary: Close service
      responses:
        '200':
          description: Success
        '500':
          description: Internal handler error

components:
  schemas:
    LoginResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: './domain.yml#/components/schemas/Owner'
      required:
        - token
        - user

    AuthRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message