openapi: 3.0.0
info:
  title: Warpnet
  version: 0.2.329
  description: External API for a distributed Twitter-like application
servers:
  - url: http://localhost:4002
    description: Interface address

paths:
  /:
    get:
      description: HTTP endpoint
      summary: Serve static files
      operationId: GetIndex
      responses:
        '200':
          description: OK

  /{file*}:
    get:
      summary: Serve static files
      operationId: GetStaticFile
      description: HTTP endpoint. Returns any static file from the /static/ directory
      parameters:
        - in: path
          name: file
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Static file served successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: File not found

  /v1/api/ws:
    get:
      summary: Serve Websocket connection
      description: HTTP to WS endpoint
      operationId: WebsocketUpgrade
      responses:
        '101':
          description: Upgraded
        '500':
          description: Internal server error

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message
