openapi: 3.0.0
info:
  title: Distributed Twitter API
  version: 1.0.0
  description: Discovery API for a distributed Twitter-like application
servers:
  - url: https://localhost:16969
    description: Local development server

paths:
  /v1/discovery/event/new:
    post:
      tags:
        - Event
      summary: Create a new user
      operationId: newEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './domain.yml#/components/schemas/Event'
      responses:
        '200':
          description: OK
        '400':
          description: Invalid input
        '401':
          description: Auth failed
        '500':
          description: Discovery server error


