openapi: 3.0.0
info:
  title: Warp Network
  version: 1.0.0
  description: P2P streaming protocols for a distributed Twitter-like application
servers:
  - url: tcp://0.0.0.0:4001
    description: IPv4 TCP server
  - url: ws://0.0.0.0:4001/ws
    description: IPv4 Websocket server
  - url: tcp://[::]:4001
    description: IPv6 TCP server

paths:
#  /user/1.0.0:
#    options:
#      requestBody:
#        content:
#          '*/*':
#            schema:
#              anyOf:
#                - $ref: './event.yml#/components/schemas/GetUserEvent'
#                - $ref: './event.yml#/components/schemas/NewUserEvent'
#                - $ref: './event.yml#/components/schemas/GetAllUsersEvent'
#      responses:
#        200:
#          description: HTTP is not supported
#          content:
#            '*/*':
#              schema:
#                anyOf:
#                  - $ref: './dto.yml#/components/schemas/UsersResponse'
#                  - $ref: './domain.yml#/components/schemas/User'

#  /tweet/1.0.0:
#    options:
#      requestBody:
#        content:
#          '*/*':
#            schema:
#              anyOf:
#                - $ref: './event.yml#/components/schemas/GetTweetEvent'
#                - $ref: './event.yml#/components/schemas/NewTweetEvent'
#                - $ref: './event.yml#/components/schemas/GetAllTweetsEvent'
#      responses:
#        200:
#          description: HTTP is not supported
#          content:
#            '*/*':
#              schema:
#                anyOf:
#                  - $ref: './dto.yml#/components/schemas/TweetsResponse'
#                  - $ref: './domain.yml#/components/schemas/Tweet'

#  /timeline/1.0.0:
#    options:
#      requestBody:
#        content:
#          '*/*':
#            schema:
#              $ref: './event.yml#/components/schemas/GetTimelineEvent'
#      responses:
#        200:
#          description: HTTP is not supported
#          content:
#            '*/*':
#              schema:
#                $ref: './dto.yml#/components/schemas/TweetsResponse'

  /node/1.0.0:
    options:
      requestBody:
        content:
          '*/*':
            schema: {}
      responses:
        200:
          description: HTTP is not supported
          content:
            '*/*':
              schema: {}

  /chat/1.0.0:
    options:
      requestBody:
        content:
          '*/*':
            schema:
              anyOf:
                - $ref: './event.yml#/components/schemas/NewChatEvent'
                - $ref: './event.yml#/components/schemas/GetChatEvent'
                - $ref: './event.yml#/components/schemas/GetAllChatsEvent'
      responses:
        200:
          description: HTTP is not supported
          content:
            '*/*':
              schema:
                anyOf:
                  - $ref: './dto.yml#/components/schemas/ChatsResponse'
                  - $ref: './domain.yml#/components/schemas/Chat'

#  /reply/1.0.0:
#    options:
#      requestBody:
#        content:
#          '*/*':
#            schema:
#              anyOf:
#                - $ref: './event.yml#/components/schemas/NewReplyEvent'
#                - $ref: './event.yml#/components/schemas/GetReplyEvent'
#                - $ref: './event.yml#/components/schemas/GetAllRepliesEvent'
#      responses:
#        200:
#          description: HTTP is not supported
#          content:
#            '*/*':
#              schema:
#                anyOf:
#                  - $ref: './dto.yml#/components/schemas/RepliesTreeResponse'
#                  - $ref: './domain.yml#/components/schemas/ReplyNode'

  /message/1.0.0:
    options:
      requestBody:
        content:
          '*/*':
            schema:
              anyOf:
                - $ref: './event.yml#/components/schemas/NewMessageEvent'
                - $ref: './event.yml#/components/schemas/GetMessageEvent'
                - $ref: './event.yml#/components/schemas/GetAllMessagesEvent'
      responses:
        200:
          description: HTTP is not supported
          content:
            '*/*':
              schema:
                anyOf:
                  - $ref: './dto.yml#/components/schemas/MessagesResponse'
                  - $ref: './domain.yml#/components/schemas/ChatMessage'

components:
  schemas:
    None:
      type: object





