#!/bin/bash

# Абсолютный путь к папке, где находится этот скрипт
DIR="$(cd "$(dirname "$0")" && pwd)"

# Запуск команды в Terminal.app через AppleScript
osascript <<EOF
tell application "Terminal"
    do script "$DIR/warpnet-darwin; read -n 1 -s -r -p \"Press any key to close...\""
    activate
end tell
EOF
