// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// FollowRequest defines model for FollowRequest.
type FollowRequest struct {
	ReaderId string `json:"reader_id"`
	WriterId string `json:"writer_id"`
}

// Like defines model for Like.
type Like struct {
	TweetId string `json:"tweet_id"`
	UserId  string `json:"user_id"`
}

// Node defines model for Node.
type Node struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Ip The IP address
	Ip string `json:"ip"`

	// IsActive Whether the IP address is currently active
	IsActive bool `json:"is_active"`

	// LastSeen The timestamp when this IP address was last active
	LastSeen time.Time `json:"last_seen"`

	// Latency The network latency to this IP in milliseconds
	Latency *int64 `json:"latency,omitempty"`
	OwnerId string `json:"owner_id"`
	Port    string `json:"port"`

	// Uptime Uptime of the node in seconds
	Uptime *int64 `json:"uptime,omitempty"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	// Ip The IP address that was pinged
	Ip string `json:"ip"`

	// Latency The latency to the IP address in milliseconds
	Latency     int64   `json:"latency"`
	Port        string  `json:"port"`
	RequesterIp *string `json:"requester_ip,omitempty"`
}

// Retweet defines model for Retweet.
type Retweet struct {
	TweetId string `json:"tweet_id"`
	UserId  string `json:"user_id"`
}

// TimelineResponse defines model for TimelineResponse.
type TimelineResponse struct {
	Cursor string  `json:"cursor"`
	Tweets []Tweet `json:"tweets"`
}

// Tweet defines model for Tweet.
type Tweet struct {
	Content       string     `json:"content"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	Likes         *[]Like    `json:"likes,omitempty"`
	LikesCount    *int64     `json:"likes_count,omitempty"`
	Retweets      *[]Retweet `json:"retweets,omitempty"`
	RetweetsCount *int64     `json:"retweets_count,omitempty"`
	Sequence      *int64     `json:"sequence,omitempty"`
	TweetId       *string    `json:"tweet_id,omitempty"`
	UserId        string     `json:"user_id"`
	Username      *string    `json:"username,omitempty"`
}

// UnfollowRequest defines model for UnfollowRequest.
type UnfollowRequest struct {
	ReaderId string `json:"reader_id"`
	WriterId string `json:"writer_id"`
}

// User defines model for User.
type User struct {
	Birthdate    *time.Time `json:"birthdate,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	Description  *string    `json:"description,omitempty"`
	Followed     *[]string  `json:"followed,omitempty"`
	FollowedNum  *int64     `json:"followed_num,omitempty"`
	Followers    *[]string  `json:"followers,omitempty"`
	FollowersNum *int64     `json:"followers_num,omitempty"`
	Link         *string    `json:"link,omitempty"`
	Location     *string    `json:"location,omitempty"`
	MyReferrals  *[]string  `json:"my_referrals,omitempty"`
	ReferredBy   *string    `json:"referred_by,omitempty"`
	UserId       *string    `json:"user_id,omitempty"`
	Username     string     `json:"username"`
}

// GetTweetsTimelineUserIdParams defines parameters for GetTweetsTimelineUserId.
type GetTweetsTimelineUserIdParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *uint64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AuthRequest

// PostNodesJSONRequestBody defines body for PostNodes for application/json ContentType.
type PostNodesJSONRequestBody = Node

// PostTweetsJSONRequestBody defines body for PostTweets for application/json ContentType.
type PostTweetsJSONRequestBody = Tweet

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = User

// PostUsersFollowJSONRequestBody defines body for PostUsersFollow for application/json ContentType.
type PostUsersFollowJSONRequestBody = FollowRequest

// PostUsersUnfollowJSONRequestBody defines body for PostUsersUnfollow for application/json ContentType.
type PostUsersUnfollowJSONRequestBody = UnfollowRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Serve the main index.html page
	// (GET /)
	GetIndex(ctx echo.Context) error
	// Store credentials
	// (POST /auth/login)
	PostAuthLogin(ctx echo.Context) error
	// Close service
	// (POST /auth/logout)
	PostAuthLogout(ctx echo.Context) error
	// Get node info
	// (GET /nodes)
	GetNodes(ctx echo.Context) error
	// Send node info
	// (POST /nodes)
	PostNodes(ctx echo.Context) error
	// Ping another node to check its status
	// (GET /nodes/ping)
	GetNodesPing(ctx echo.Context) error
	// Publish a new tweet
	// (POST /tweets)
	PostTweets(ctx echo.Context) error
	// Get user's tweet timeline
	// (GET /tweets/timeline/{user_id})
	GetTweetsTimelineUserId(ctx echo.Context, userId string, params GetTweetsTimelineUserIdParams) error
	// Get user's tweets
	// (GET /tweets/{user_id})
	GetTweetsUserId(ctx echo.Context, userId string) error
	// Get a certain tweet
	// (GET /tweets/{user_id}/{tweet_id})
	GetTweetsUserIdTweetId(ctx echo.Context, userId string, tweetId string) error
	// Create a new user
	// (POST /users)
	PostUsers(ctx echo.Context) error
	// Follow another user
	// (POST /users/follow)
	PostUsersFollow(ctx echo.Context) error
	// Unfollow a user
	// (POST /users/unfollow)
	PostUsersUnfollow(ctx echo.Context) error
	// Get user information
	// (GET /users/{user_id})
	GetUsersUserId(ctx echo.Context, userId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetIndex converts echo context to params.
func (w *ServerInterfaceWrapper) GetIndex(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIndex(ctx)
	return err
}

// PostAuthLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthLogin(ctx)
	return err
}

// PostAuthLogout converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthLogout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthLogout(ctx)
	return err
}

// GetNodes converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodes(ctx)
	return err
}

// PostNodes converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodes(ctx)
	return err
}

// GetNodesPing converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodesPing(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodesPing(ctx)
	return err
}

// PostTweets converts echo context to params.
func (w *ServerInterfaceWrapper) PostTweets(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTweets(ctx)
	return err
}

// GetTweetsTimelineUserId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTweetsTimelineUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTweetsTimelineUserIdParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTweetsTimelineUserId(ctx, userId, params)
	return err
}

// GetTweetsUserId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTweetsUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTweetsUserId(ctx, userId)
	return err
}

// GetTweetsUserIdTweetId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTweetsUserIdTweetId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// ------------- Path parameter "tweet_id" -------------
	var tweetId string

	err = runtime.BindStyledParameterWithOptions("simple", "tweet_id", ctx.Param("tweet_id"), &tweetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tweet_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTweetsUserIdTweetId(ctx, userId, tweetId)
	return err
}

// PostUsers converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsers(ctx)
	return err
}

// PostUsersFollow converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersFollow(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersFollow(ctx)
	return err
}

// PostUsersUnfollow converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersUnfollow(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersUnfollow(ctx)
	return err
}

// GetUsersUserId converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsersUserId(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/", wrapper.GetIndex)
	router.POST(baseURL+"/auth/login", wrapper.PostAuthLogin)
	router.POST(baseURL+"/auth/logout", wrapper.PostAuthLogout)
	router.GET(baseURL+"/nodes", wrapper.GetNodes)
	router.POST(baseURL+"/nodes", wrapper.PostNodes)
	router.GET(baseURL+"/nodes/ping", wrapper.GetNodesPing)
	router.POST(baseURL+"/tweets", wrapper.PostTweets)
	router.GET(baseURL+"/tweets/timeline/:user_id", wrapper.GetTweetsTimelineUserId)
	router.GET(baseURL+"/tweets/:user_id", wrapper.GetTweetsUserId)
	router.GET(baseURL+"/tweets/:user_id/:tweet_id", wrapper.GetTweetsUserIdTweetId)
	router.POST(baseURL+"/users", wrapper.PostUsers)
	router.POST(baseURL+"/users/follow", wrapper.PostUsersFollow)
	router.POST(baseURL+"/users/unfollow", wrapper.PostUsersUnfollow)
	router.GET(baseURL+"/users/:user_id", wrapper.GetUsersUserId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZb2/bvBH/KgQ3YBvgRE6bJ3jqd1m3dQGyIugS9EUXGIx4tthQpEqe4hiBv/tA6r9F",
	"27ITF33eBLJ0PB5/9+P9ywuNdZppBQotnbxQGyeQMv94mWPyBX7kYNH9zIzOwKAA/zFj1i604e4ZlxnQ",
	"CbVohJrT1YjmFoxiKQQ+rkbUwI9cGOB08q2RHDUa70fVIv3wHWJ0Gv9pjDZ9K2LN25sIhTAH4xakYC2b",
	"D7DAq2jkQ5v/S0upFxuhMMA4mKnwWKRCXYOaY0InZ6M+MgsjcJjsmpnNJm0lIWuvxSP0jcQFAA6z0fnk",
	"AAurZaNmr5B5n0uXrTnSAEPgU+bxnWmTuifKGcIJCs+Pnp0ic7IcbGxEhkIrOqG3CZCrG8I4N2AtHTWq",
	"RPZ0HtRipyxG8QR9ZV8TwAQMwY5SIiyJc2NAoVyScm2t+EFrCUw5zZJZnFoAFTbTHcsiSzOySEARTIRt",
	"77JgljgNzQ7DUJEMQcXL8J4KcKHNIymFCOp6X6FIKqQUFmKtuIMOnlmaSaCTs3fjNpAKL1pItu6cXqia",
	"OT27Mm2wMGrGcol0cvHh4kOIfZk/Wc/8O/+e6Jl3h9IcnMkBa99fjIeYu8ZekdHSxjYl2k5snS/E6xuh",
	"5l/AZlrZAL93c5VgwtB7PRNqDnwId7f6uuPjLoF7rh7g3KH+M0WYdEBlu6Ovh706RrlJCN0v4IPKLxzX",
	"bkUKUijYzIE4N7ZIYj3TvOaCKAipf/izgRmd0D9FTX6OyuQc3XosVrUVzBi27Ge2Yr9ae9DqMKqxVggK",
	"B4B6SOCW4hGGH9bns95ZSy3TWOequ3VF4VQokeYpnYxDdDawJ+YVAwOWVLoONsa6O6NiOGDpEfi/b/1W",
	"XI6KMiGW3anZH6qEurMQKDYfhMHEEXs40w+5HZ1IHogVBZTAO8ztR5Q1jlarpspR6WVIxC+XGHvQTsbu",
	"sZUU6rEjmhsZjBw6ZhuBSZdTAzMwhsk9TS6WAZ8+LDf2M5vqmvZd2Tet+HV9AjpRoWa6n9cvb67ITBvC",
	"CBdO70OOwMntQiCCOXERkbAsk6JEaURRoKuJ6D/64uTy5oqO6BMYWyg/Ox2fjn0dl4FimaAT+t6/cr0Z",
	"Jh7KyP2ZA4ZKDmEJKJ5poZBYME9gfeGRMqHIzPjwwEnG5nUR1zKV/FUoDs+nCabyb6fU22D8lytOJ/QT",
	"4JX7Th2GRX715rwbj9fSFcIzRk5L08y6p7o6pP/Lx+P3sZPwT1D+Bsbbvz1uxYsKro9Sq/Jr1PpcvllX",
	"8KD5svj9FWSsU3B1WEhVI1hpqk3r34DVenzwlZ5H+N+3/7nehK5z6m89qFoC0XdbXKoGsXCjXeP42ziY",
	"jlptdwP5lULHdUn+61hhSNHMhy5I4CJ0j1tqAK/BfbZ5mjKzrD41jGv45FHxwhHLMYmkngt/2EwXuajL",
	"tRtt8TLH5NqL1QXt3zVf7gXgtmKiPVpZdSMDmhxWO2l++NY+twWQde8JB2RCWufJ8/FZIP7kmJAZExJ4",
	"i1NdmdrbdouvUBsgsQEOCoWL1yOKbG5dYHR70PuOu3SOg/zl5MLQrbEoj2Ow9lVH+Ci1BS8gYgib75pU",
	"2wqYvZj22Qu80tmDqlc/dek3DP371SBzPj7vI/NZI5npXG12/5Yb+gmwatxnugWZN+7e95ibHNwg9faX",
	"scBm8C3cAliQSk9MCk6EynLsRSzFtwFScyjKXIDcRaQbJ3TEyNGZcAS4476TaneX8dN6VLOFT9xJlKQi",
	"2vgfhRJeVlgHX1FvEFPaD/E8zqhJnED8SARaYpFhbsOwN83hZk7eFjLHIWXZ4v/c3NDadK3KcB+ILbg+",
	"y6VckrK1OYj4N/mDFDYhjChYkKKvbtxQWNH2Q4TlcCV6KUvx1bbbUDimGsi4xHbFfRFrWAroG5pvL9TV",
	"AL6wpSNaFPCtbraL+aiFX69oKTX9yMEsG1X18GXvlVKkAjsL65Hbu37NNaLPJ3N9Ur7NixZrtbo/JkvW",
	"J10bqom/2MK1pPLexijgaw9tasEmIgQySB5UvZU+e7DmyGy5/xnJftN4sOela2HRtQttSO1uL3mxwT6y",
	"A30TvVSzrMFu8s8/4W53NdUjtzdw/M4wOwOMkwPDrPMEIzEYdA3RtjDrwNmR7e68yHGSXdOT/CJ90Jtl",
	"uo9+bZnoHMotB3gLWvhHxeRsgBuKf0gfyRnd/3YP8srZxrq4JHE5fPT1oEfhECwLw+qCbheauRqMZzWf",
	"Pha918bfr+w1Ckyr470W1co4wnYiOiiNFoD+2ln0beYjm1LkrsTouz2T1iPaNbj9/4NcT1NAtpaxdcwk",
	"4fAEUmcpVJNW57bcSDqhCWI2iSLp5BJtcfL7+PcxXd2v/h8AAP//+wC5XOkjAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
