// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// FollowRequest defines model for FollowRequest.
type FollowRequest struct {
	ReaderId string `json:"reader_id"`
	WriterId string `json:"writer_id"`
}

// Like defines model for Like.
type Like struct {
	TweetId string `json:"tweet_id"`
	UserId  string `json:"user_id"`
}

// Node defines model for Node.
type Node struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Ip The IP address
	Ip string `json:"ip"`

	// IsActive Whether the IP address is currently active
	IsActive bool `json:"is_active"`

	// LastSeen The timestamp when this IP address was last active
	LastSeen time.Time `json:"last_seen"`

	// Latency The network latency to this IP in milliseconds
	Latency *int64 `json:"latency,omitempty"`
	OwnerId string `json:"owner_id"`

	// Uptime Uptime of the node in seconds
	Uptime *int64 `json:"uptime,omitempty"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	// Ip The IP address that was pinged
	Ip string `json:"ip"`

	// Latency The latency to the IP address in milliseconds
	Latency int64 `json:"latency"`
}

// Retweet defines model for Retweet.
type Retweet struct {
	TweetId string `json:"tweet_id"`
	UserId  string `json:"user_id"`
}

// TimelineResponse defines model for TimelineResponse.
type TimelineResponse struct {
	Cursor string  `json:"cursor"`
	Tweets []Tweet `json:"tweets"`
}

// Tweet defines model for Tweet.
type Tweet struct {
	Content       string     `json:"content"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	Likes         *[]Like    `json:"likes,omitempty"`
	LikesCount    *int64     `json:"likes_count,omitempty"`
	Retweets      *[]Retweet `json:"retweets,omitempty"`
	RetweetsCount *int64     `json:"retweets_count,omitempty"`
	Sequence      *int64     `json:"sequence,omitempty"`
	TweetId       *string    `json:"tweet_id,omitempty"`
	UserId        string     `json:"user_id"`
	Username      *string    `json:"username,omitempty"`
}

// UnfollowRequest defines model for UnfollowRequest.
type UnfollowRequest struct {
	ReaderId string `json:"reader_id"`
	WriterId string `json:"writer_id"`
}

// User defines model for User.
type User struct {
	Birthdate    *time.Time `json:"birthdate,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	Description  *string    `json:"description,omitempty"`
	Followed     *[]string  `json:"followed,omitempty"`
	FollowedNum  *int64     `json:"followed_num,omitempty"`
	Followers    *[]string  `json:"followers,omitempty"`
	FollowersNum *int64     `json:"followers_num,omitempty"`
	Link         *string    `json:"link,omitempty"`
	Location     *string    `json:"location,omitempty"`
	MyReferrals  *[]string  `json:"my_referrals,omitempty"`
	ReferredBy   *string    `json:"referred_by,omitempty"`
	UserId       *string    `json:"user_id,omitempty"`
	Username     string     `json:"username"`
}

// GetNodesPingParams defines parameters for GetNodesPing.
type GetNodesPingParams struct {
	Ip string `form:"ip" json:"ip"`
}

// GetTweetsTimelineUserIdParams defines parameters for GetTweetsTimelineUserId.
type GetTweetsTimelineUserIdParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *uint64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AuthRequest

// PostNodesJSONRequestBody defines body for PostNodes for application/json ContentType.
type PostNodesJSONRequestBody = Node

// PostNodesPingJSONRequestBody defines body for PostNodesPing for application/json ContentType.
type PostNodesPingJSONRequestBody = Node

// PostTweetsJSONRequestBody defines body for PostTweets for application/json ContentType.
type PostTweetsJSONRequestBody = Tweet

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = User

// PostUsersFollowJSONRequestBody defines body for PostUsersFollow for application/json ContentType.
type PostUsersFollowJSONRequestBody = FollowRequest

// PostUsersUnfollowJSONRequestBody defines body for PostUsersUnfollow for application/json ContentType.
type PostUsersUnfollowJSONRequestBody = UnfollowRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Serve the main index.html page
	// (GET /)
	GetIndex(ctx echo.Context) error
	// Store credentials
	// (POST /auth/login)
	PostAuthLogin(ctx echo.Context) error
	// Close service
	// (POST /auth/logout)
	PostAuthLogout(ctx echo.Context) error
	// Get node info
	// (GET /nodes)
	GetNodes(ctx echo.Context) error
	// Send node info
	// (POST /nodes)
	PostNodes(ctx echo.Context) error
	// Ping another node to check its status
	// (GET /nodes/ping)
	GetNodesPing(ctx echo.Context, params GetNodesPingParams) error
	// Send node status
	// (POST /nodes/ping)
	PostNodesPing(ctx echo.Context) error
	// Publish a new tweet
	// (POST /tweets)
	PostTweets(ctx echo.Context) error
	// Get user's tweet timeline
	// (GET /tweets/timeline/{user_id})
	GetTweetsTimelineUserId(ctx echo.Context, userId string, params GetTweetsTimelineUserIdParams) error
	// Get user's tweets
	// (GET /tweets/{user_id})
	GetTweetsUserId(ctx echo.Context, userId string) error
	// Get a certain tweet
	// (GET /tweets/{user_id}/{tweet_id})
	GetTweetsUserIdTweetId(ctx echo.Context, userId string, tweetId string) error
	// Create a new user
	// (POST /users)
	PostUsers(ctx echo.Context) error
	// Follow another user
	// (POST /users/follow)
	PostUsersFollow(ctx echo.Context) error
	// Unfollow a user
	// (POST /users/unfollow)
	PostUsersUnfollow(ctx echo.Context) error
	// Get user information
	// (GET /users/{user_id})
	GetUsersUserId(ctx echo.Context, userId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetIndex converts echo context to params.
func (w *ServerInterfaceWrapper) GetIndex(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIndex(ctx)
	return err
}

// PostAuthLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthLogin(ctx)
	return err
}

// PostAuthLogout converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthLogout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthLogout(ctx)
	return err
}

// GetNodes converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodes(ctx)
	return err
}

// PostNodes converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodes(ctx)
	return err
}

// GetNodesPing converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodesPing(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNodesPingParams
	// ------------- Required query parameter "ip" -------------

	err = runtime.BindQueryParameter("form", true, true, "ip", ctx.QueryParams(), &params.Ip)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ip: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodesPing(ctx, params)
	return err
}

// PostNodesPing converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodesPing(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodesPing(ctx)
	return err
}

// PostTweets converts echo context to params.
func (w *ServerInterfaceWrapper) PostTweets(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTweets(ctx)
	return err
}

// GetTweetsTimelineUserId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTweetsTimelineUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTweetsTimelineUserIdParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTweetsTimelineUserId(ctx, userId, params)
	return err
}

// GetTweetsUserId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTweetsUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTweetsUserId(ctx, userId)
	return err
}

// GetTweetsUserIdTweetId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTweetsUserIdTweetId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// ------------- Path parameter "tweet_id" -------------
	var tweetId string

	err = runtime.BindStyledParameterWithOptions("simple", "tweet_id", ctx.Param("tweet_id"), &tweetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tweet_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTweetsUserIdTweetId(ctx, userId, tweetId)
	return err
}

// PostUsers converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsers(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsers(ctx)
	return err
}

// PostUsersFollow converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersFollow(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersFollow(ctx)
	return err
}

// PostUsersUnfollow converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersUnfollow(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersUnfollow(ctx)
	return err
}

// GetUsersUserId converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsersUserId(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/", wrapper.GetIndex)
	router.POST(baseURL+"/auth/login", wrapper.PostAuthLogin)
	router.POST(baseURL+"/auth/logout", wrapper.PostAuthLogout)
	router.GET(baseURL+"/nodes", wrapper.GetNodes)
	router.POST(baseURL+"/nodes", wrapper.PostNodes)
	router.GET(baseURL+"/nodes/ping", wrapper.GetNodesPing)
	router.POST(baseURL+"/nodes/ping", wrapper.PostNodesPing)
	router.POST(baseURL+"/tweets", wrapper.PostTweets)
	router.GET(baseURL+"/tweets/timeline/:user_id", wrapper.GetTweetsTimelineUserId)
	router.GET(baseURL+"/tweets/:user_id", wrapper.GetTweetsUserId)
	router.GET(baseURL+"/tweets/:user_id/:tweet_id", wrapper.GetTweetsUserIdTweetId)
	router.POST(baseURL+"/users", wrapper.PostUsers)
	router.POST(baseURL+"/users/follow", wrapper.PostUsersFollow)
	router.POST(baseURL+"/users/unfollow", wrapper.PostUsersUnfollow)
	router.GET(baseURL+"/users/:user_id", wrapper.GetUsersUserId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RabW8buRH+KwRboC2gZOUkdzjoW5q2VwNuYKQO7sPVEOjlSMuYS27IWSuCof9ekNxX",
	"LVdaKVGQol+MfRkOZ59nOG/yM011XmgFCi1dPFObZpAzf/m2xOwDfC7BorstjC7AoAD/smDWbrTh7hq3",
	"BdAFtWiEWtPdjJYWjGI5RF7uZtTA51IY4HTxeys5azXez+pF+uETpOg0/t0YbYZWpJp3NxEKYQ3GLcjB",
	"WraeYIFX0crHNv+HllJvRqEwwDiYpfBY5ELdgFpjRhdXsyEyGyNwmuyeme0mXSUxa2/EIwyNxA0ATrPR",
	"cXKGhfWyWbtXzLz3FWV7RBpgCHzJPL4rbXJ3RTlDeIHC+8fATlE4WQ42NaJAoRVd0LsMyPUtYZwbsJbO",
	"WlWieHoT1WKXLEXxBENlv2WAGRiCPaVEWJKWxoBCuSXV2kbxg9YSmHKaJbO4tAAqbqb7LIssL8gmA0Uw",
	"E7a7y4ZZ4jS0O0xDRTIElW7jeyrAjTaPpBIiqJt9hSK5kFJYSLXiDjr4wvJCAl1cvZp3gVT4cwfJzpnT",
	"G9V4ztCrCm/xwKyP/jnRKw+z0hycKRErXv88n2LGnleKgnY57rLSMTjmqLdCrT+ALbSyEYc97nwEM4ae",
	"xkKoNfApzniQvB5pfY8ccHcWTPXuMTQ+gD/VP3BguRM5SKFgnLO0NDZkkYFpXnMgFiH3F380sKIL+oek",
	"TZBJlR2TO4/FrrGCGcO2w9QS9mu0R62Oo5pqhaBwAqjnRE4pHmH6x/qEMvjWSssy1aXqb127XC6UyMuc",
	"LuaxYGHgRMxrD4xYUus62xjrcrtK4YylF/D/UwuocDhql4l52Ue1+p+qYT5aiFR7D8Jg5hx7uqefczp6",
	"kTcSKwKUwHueO4woez5ar1oq50rPU/JptcTYs3Yy9oStpFCPPdHSyGjk0CkbBSbfLg2swBgmTzQ5LAO+",
	"fNiONhSjhUXnrJyaVvy6oQM6UaFWepiH395ek5U2hBEunN6HEoGTu41ABPPCRUTCikKKCqUZRYGueKF/",
	"G4qTt7fXdEafwNig/Orl/OXcF1IFKFYIuqCv/SPXHGHmoUzcn3VIGfslgrAEFC+0UEgsmCewvlDImVBk",
	"ZXx44KRg66ba6phK/iwUhy8vM8zlX15Sb4Pxb645XdBfAa/de+owDPnVm/NqPt9LVwhfMHFa2m7SXTVl",
	"HP1POZ+/Tp2Ev4LqHhjv3nvcwoMarndSq+pt0nldPdlX8KD5Ntz/BjLVObi6KaaqFaw1NaYNT8BuPz74",
	"yswj/M+7f92MoetI/WkAVUcg+WTDoWoRi3e6DY4/zaPpqNP3tpBfK3S+Lsm/nVcYErrp2AGJHIT+51Ya",
	"wGtwr22Z58xs61etx7X+5FHxwgkrMUukXgv/sYUOuajva7fa4tsSsxsvFg4tWPyr5tuTADxUTHRnG7t+",
	"ZEBTwu6om5+/tc9tEWTdc8IBmZDWMflmfhWJPyVmZMWEBN7xqb5Mw7Y9wBVqAyQ1wEGhcPF6RpGtrQuM",
	"bg9636NLlziJLycXh27Pi8o0df3513zCO6kteAGRQtx8103aTsAcxLT3XuAryZ5Uvfqxx7BhGJ6vFpk3",
	"8zdDZN5rJCtdqnH6D5zQXwHrDnulO5B54+53swMEt0h9+8MYsJl8Cg8AFnWlJyYFJ0IVJQ4iluKHAGl8",
	"KHEt/FFHunVCLlcblgP6uu33Z+pCHf1cgtnSGQ2FSmi3+x8764B1cKzQnZSg9sOF46OF3f0FI1pvUhLx",
	"afee1Lu7SiRvvuCAn3MnUTk70cbfBCW8qvzODh3eIKa0n+7VQKYZpI9EoCUWGZb2jPNROcAPcEb+P3lt",
	"z/MYhe5Et3OHcTrvgsxluKymR9+XzM6me+HFvSA2hNFVKeWWVF3zWTH1tnyQwmaEEQUbEkY2LQ3Bii4P",
	"CVZzu+S56vJ2hwJtIKae9bma6ZqPxFzXM7Uhtx2UjMfdQT0cj97NXO/klVLkAmk/1K9YKZEuXg3L+Rn9",
	"8mKtX1RPy9C9XzaUD4aoI4Xqn2ygltTsjR54X9Zq0wi2hz9SnJRR1Qfd5wSvubC33H+POnJs8jxg6UZY",
	"dLVCF1J7nCUvNpkjO5Gb5Lkek06myV9/h7Pd19RMc78B8UfD7Aowzc4Ms44JRlIw6HrtQ2HWgXMk2330",
	"IpdJdm27+4O02N8s073za6tE51DuEOAt6OCfhKHsBBrCPxtciIz+fzJMYuVqtOWqnLiaa/vSz6NwDpbB",
	"sKYmP4ZmqSbjWf/0cSn33vtl5Svb2IBp/Xlfi2ptHGFHEZ2URgOgP3YW/Tajt7EUeSwx+kGC68Sr6f8e",
	"3P6nRte+BMj2MrZOmSQcnkDqIod6iO9oK42kC5ohFoskkU4u0xYXv8x/mdPd/e6/AQAA///Af/nqxSUA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
