name: Build, Push and Deploy to Droplet

on:
  workflow_dispatch: # Запуск вручную

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: --dns 8.8.8.8

      - name: Set up SSH agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_1 }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.HOST_2 }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.HOST_3 }} >> ~/.ssh/known_hosts
      

      - name: Deploy to Droplet
        run: |
          scp ./deploy.sh root@${{ secrets.HOST_1 }}:/root
          scp ./deploy.sh root@${{ secrets.HOST_2 }}:/root
          scp ./deploy.sh root@${{ secrets.HOST_3 }}:/root
          ssh root@${{ secrets.HOST_1 }} 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} HOST=${{ secrets.HOST_1 }} bash /root/deploy.sh'
          ssh root@${{ secrets.HOST_2 }} 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} HOST=${{ secrets.HOST_2 }} bash /root/deploy.sh'
          ssh root@${{ secrets.HOST_3 }} 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} HOST=${{ secrets.HOST_3 }} bash /root/deploy.sh'
