name: Build, Push and Deploy to Droplet

on:
  workflow_dispatch: # Запуск вручную

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: --dns 8.8.8.8

      - name: Set up SSH agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 67.207.72.168 >> ~/.ssh/known_hosts
          ssh-keyscan -H 167.99.29.177 >> ~/.ssh/known_hosts
          ssh-keyscan -H 188.166.204.43 >> ~/.ssh/known_hosts
      

      - name: Deploy to Droplet
        run: |
          scp ./deploy.sh root@67.207.72.168:/root
          scp ./deploy.sh root@167.99.29.177:/root
          scp ./deploy.sh root@188.166.204.43:/root
          ssh root@67.207.72.168 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} bash /root/deploy.sh'
          ssh root@167.99.29.177 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} bash /root/deploy.sh'
          ssh root@188.166.204.43 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} bash /root/deploy.sh'
